version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: HowWentParty
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  django:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile이 있는 경로를 지정해야 함
    command: python manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DJANGO_DB_PORT: 5432
      DJANGO_DB_NAME: HowWentParty
      DJANGO_DB_USER: admin
      DJANGO_DB_PASSWORD: '1234'
      REDIS_HOST: redis
      REDIS_PORT: 6379


