# Generated by Django 4.0.3 on 2023-11-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_party_item', '0002_alter_productimage_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product_image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='product_party_item.product'),
        ),
    ]
