# Generated by Django 4.0.3 on 2023-11-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='UserClassification',
            field=models.CharField(choices=[{'파티장', 'PartyLeader'}, {'회원', 'Member'}, {'Seller', '판매자'}], default='Member', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(choices=[(0, 'none'), (10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70+')], default='0'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='temp_username', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', '남자'), ('female', '여자')], max_length=6),
        ),
    ]
