# Generated by Django 4.0.3 on 2023-11-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='UserClassification',
            new_name='user_classification',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
