# Generated by Django 4.0.3 on 2023-11-24 06:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_user_nick_name_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='static/images/default_gray.png', upload_to=accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(choices=[(0, 'none'), (10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70+')], default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_nick_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
